### ISSUE TITLE
Having issue importing RTLSSensor because of compiler version

### ISSUE THREAD

**Issue by ConanChen8** [coreaiot/RTLSSensor#1]
I installed this framework with pod following steps in README. After installation, I imported RTLSSensor but it gives me "Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.5.1 compiler"

I am using macOS Big Sur 11.5.2 and Xcode Version 13.1
Happens on both emulator and real device.
Please help.

<img width="671" alt="Screen Shot 2021-12-08 at 11 01 25 PM" src="https://user-images.githubusercontent.com/13328966/145332302-c0e7b6c5-35a6-4205-8b06-7e5a58949662.png">

**Comment by kuyoonjo** [comment]
> I installed this framework with pod following steps in README. After installation, I imported RTLSSensor but it gives me "Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.5.1 compiler"
> 
> I am using macOS Big Sur 11.5.2 and Xcode Version 13.1 Happens on both emulator and real device. Please help.
> 
> <img alt="Screen Shot 2021-12-08 at 11 01 25 PM" width="671" src="https://user-images.githubusercontent.com/13328966/145332302-c0e7b6c5-35a6-4205-8b06-7e5a58949662.png">

您好，请联系下我们 FAE 同事。

**Comment by ConanChen8** [comment]
好的 感谢你的回复

**Comment by kuyoonjo** [comment]
已更新 1.0.2 版本，使用 Swift 5.5.1。
